.TH vym 1 "August 5, 2005" vym 1
.SH NAME
vym \- View your mind
.SH SYNOPSIS
.B vym
.SH DESCRIPTION
This manual page documents briefly the
.B vym
program
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBvym\fP is a program that makes mindmapping possible. It is based on qt
and it can be used by everyone for structure work.
.SH OPTIONS
For more information, see /usr/share/vym/doc/vym.pdf .
.TP
.B \-h, \-\-help
Show a small help.
.TP
.B \-v, \-\-version
Show version of vym.
.SH AUTHOR
vym was written by <Uwe Drechsler>.
.PP
This manual page was written by Steffen Joeris <steffen.joeris@skolelinux.de>,
for the Debian project (but may be used by others).
